In [ ]:
print("working")

In [ ]:
print("working")

In [1]:
import pandas as pd
df = pd.read_excel("../data/raw/loan.xlsx")
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599,5000,5000,4975.0,36 months,0.1065,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,0.1527,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,0.1596,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,0.1349,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,0.1269,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN

In [2]:
df.shape

(39717, 111)

In [3]:
df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
       'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens',
       'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit'],
      dtype='str', length=111)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: datetime64[us](5), float64(76), int64(13), object(2), str(15)
memory usage: 33.6+ MB

In [5]:
df.isnull().sum()

id                                0
member_id                         0
loan_amnt                         0
funded_amnt                       0
funded_amnt_inv                   0
                              ...
tax_liens                        39
tot_hi_cred_lim               39717
total_bal_ex_mort             39717
total_bc_limit                39717
total_il_high_credit_limit    39717
Length: 111, dtype: int64

In [6]:
df.shape

(39717, 111)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: datetime64[us](5), float64(76), int64(13), object(2), str(15)
memory usage: 33.6+ MB

In [8]:
df.isnull().sum().sort_values(ascending=False).head(30)

num_il_tl                         39717
num_bc_sats                       39717
num_bc_tl                         39717
num_actv_bc_tl                    39717
num_accts_ever_120_pd             39717
mths_since_recent_revol_delinq    39717
num_actv_rev_tl                   39717
mths_since_recent_inq             39717
num_tl_90g_dpd_24m                39717
num_tl_30dpd                      39717
num_tl_120dpd_2m                  39717
num_sats                          39717
num_rev_tl_bal_gt_0               39717
num_rev_accts                     39717
pct_tl_nvr_dlq                    39717
mo_sin_old_il_acct                39717
mo_sin_old_rev_tl_op              39717
mo_sin_rcnt_rev_tl_op             39717
mo_sin_rcnt_tl                    39717
mths_since_recent_bc              39717
mort_acc                          39717
mths_since_recent_bc_dlq          39717
bc_util                           39717
total_rev_hi_lim                  39717
all_util                          39717
bc_open_to_buy                    39717
avg_cur_bal                       39717
acc_open_past_24mths              39717
inq_last_12m                      39717
total_cu_tl                       39717
dtype: int64

In [9]:
selected_cols = [
    'loan_amnt',
    'funded_amnt',
    'term',
    'int_rate',
    'installment',
    'grade',
    'sub_grade',
    'emp_length',
    'home_ownership',
    'annual_inc',
    'verification_status',
    'loan_status',
    'purpose',
    'dti',
    'delinq_2yrs',
    'open_acc',
    'pub_rec',
    'revol_bal',
    'revol_util',
    'total_acc',
    'application_type',
    'mort_acc',
    'pub_rec_bankruptcies',
    'addr_state'
]

loan_df = df[selected_cols].copy()
loan_df.head()

,loan_amnt,funded_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,...,delinq_2yrs,open_acc,pub_rec,revol_bal,revol_util,total_acc,application_type,mort_acc,pub_rec_bankruptcies,addr_state
0,5000,5000,36 months,0.1065,162.87,B,B2,10+ years,RENT,24000.0,...,0,3,0,13648,0.837,9,INDIVIDUAL,NaN,0.0,AZ
1,2500,2500,60 months,0.1527,59.83,C,C4,< 1 year,RENT,30000.0,...,0,3,0,1687,0.094,4,INDIVIDUAL,NaN,0.0,GA
2,2400,2400,36 months,0.1596,84.33,C,C5,10+ years,RENT,12252.0,...,0,2,0,2956,0.985,10,INDIVIDUAL,NaN,0.0,IL
3,10000,10000,36 months,0.1349,339.31,C,C1,10+ years,RENT,49200.0,...,0,10,0,5598,0.210,37,INDIVIDUAL,NaN,0.0,CA
4,3000,3000,60 months,0.1269,67.79,B,B5,1 year,RENT,80000.0,...,0,15,0,27783,0.539,38,INDIVIDUAL,NaN,0.0,OR

In [10]:
df.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_il_6m',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit']

In [11]:
for col in df.columns:
    print(col)

id
member_id
loan_amnt
funded_amnt
funded_amnt_inv
term
int_rate
installment
grade
sub_grade
emp_title
emp_length
home_ownership
annual_inc
verification_status
issue_d
loan_status
pymnt_plan
url
desc
purpose
title
zip_code
addr_state
dti
delinq_2yrs
earliest_cr_line
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
revol_util
total_acc
initial_list_status
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_d
last_pymnt_amnt
next_pymnt_d
last_credit_pull_d
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
application_type
annual_inc_joint
dti_joint
verification_status_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_il_6m
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats
num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit

In [12]:
loan_df.shape

(39717, 24)

In [13]:
loan_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   loan_amnt             39717 non-null  int64
 1   funded_amnt           39717 non-null  int64
 2   term                  39717 non-null  str
 3   int_rate              39717 non-null  float64
 4   installment           39717 non-null  float64
 5   grade                 39717 non-null  str
 6   sub_grade             39717 non-null  str
 7   emp_length            38642 non-null  str
 8   home_ownership        39717 non-null  str
 9   annual_inc            39717 non-null  float64
 10  verification_status   39717 non-null  str
 11  loan_status           39717 non-null  str
 12  purpose               39717 non-null  str
 13  dti                   39717 non-null  float64
 14  delinq_2yrs           39717 non-null  int64
 15  open_acc              39717 non-null  int64
 16  pub_rec               39717 non-null  int64
 17  revol_bal             39717 non-null  int64
 18  revol_util            39667 non-null  float64
 19  total_acc             39717 non-null  int64
 20  application_type      39717 non-null  str
 21  mort_acc              0 non-null      float64
 22  pub_rec_bankruptcies  39020 non-null  float64
 23  addr_state            39717 non-null  str
dtypes: float64(7), int64(7), str(10)
memory usage: 7.3 MB

In [14]:
loan_df.isnull().sum().sort_values(ascending=False)

mort_acc                39717
emp_length               1075
pub_rec_bankruptcies      697
revol_util                 50
int_rate                    0
loan_amnt                   0
term                        0
funded_amnt                 0
sub_grade                   0
grade                       0
installment                 0
home_ownership              0
purpose                     0
annual_inc                  0
verification_status         0
loan_status                 0
open_acc                    0
delinq_2yrs                 0
dti                         0
pub_rec                     0
total_acc                   0
revol_bal                   0
application_type            0
addr_state                  0
dtype: int64

In [15]:
loan_df['loan_status'].value_counts()

loan_status
Fully Paid     32950
Charged Off     5627
Current         1140
Name: count, dtype: int64

In [16]:
def categorize_status(status):
    if status == 'Fully Paid':
        return 'Low Risk'
    elif status == 'Charged Off':
        return 'High Risk'
    else:
        return 'Medium Risk'

loan_df['risk_category'] = loan_df['loan_status'].apply(categorize_status)

In [17]:
loan_df['risk_category'].value_counts()

risk_category
Low Risk       32950
High Risk       5627
Medium Risk     1140
Name: count, dtype: int64

In [18]:
loan_df['lti_ratio'] = loan_df['loan_amnt'] / loan_df['annual_inc']

In [19]:
loan_df['risk_category'].value_counts(normalize=True) * 100

risk_category
Low Risk       82.961956
High Risk      14.167737
Medium Risk     2.870307
Name: proportion, dtype: float64

In [20]:
loan_df.groupby('risk_category')['loan_amnt'].mean()

risk_category
High Risk      12104.385108
Low Risk       10866.455994
Medium Risk    17053.991228
Name: loan_amnt, dtype: float64

In [21]:
loan_df.groupby('risk_category')['annual_inc'].mean()

risk_category
High Risk      62427.298034
Low Risk       69862.503328
Medium Risk    75430.665105
Name: annual_inc, dtype: float64

In [22]:
loan_df.groupby('risk_category')['int_rate'].mean()

risk_category
High Risk      0.138204
Low Risk       0.116098
Medium Risk    0.150315
Name: int_rate, dtype: float64

In [23]:
loan_df.to_csv("../data/processed/cleaned_loan_data.csv", index=False)